apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jango-mart
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jango-mart
    spec:
      containers:
      - name: jango-mart-pod
        image: 785063031912.dkr.ecr.us-east-2.amazonaws.com/jangomart/jango-app:latest
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: jango-mart-service
spec:
  selector:
    app: jango-mart
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
